config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :reactions
  root to: 'readings#index'
  resources :readings
end

app/models/reading.rb
# frozen_string_literal: true

class Reading < ApplicationRecord
  has_rich_text :body
  has_many :reactions
  has_many :sections

  validates :date, presence: true
end

app/controllers/readings_controller.rb
# frozen_string_literal: true

class ReadingsController < ApplicationController
  before_action :set_books, only: %i[show]
  before_action :set_reading, only: %i[show edit update destroy]

  # GET /readings
  # GET /readings.json
  def index
    @readings = Reading.order(date: :desc).limit(10)
  end

  # GET /readings/1
  # GET /readings/1.json
  def show; end

  # GET /readings/new
  def new
    @reading = Reading.new
  end

  # GET /readings/1/edit
  def edit; end

  # POST /readings
  # POST /readings.json
  def create
    @reading = Reading.new(reading_params)

    respond_to do |format|
      if @reading.save
        format.html { redirect_to @reading, notice: 'Reading was successfully created.' }
        format.json { render :show, status: :created, location: @reading }
      else
        format.html { render :new }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /readings/1
  # PATCH/PUT /readings/1.json
  def update
    respond_to do |format|
      if @reading.update(reading_params)
        format.html { redirect_to @reading, notice: 'Reading was successfully updated.' }
        format.json { render :show, status: :ok, location: @reading }
      else
        format.html { render :edit }
        format.json { render json: @reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /readings/1
  # DELETE /readings/1.json
  def destroy
    @reading.destroy
    respond_to do |format|
      format.html { redirect_to readings_url, notice: 'Reading was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_books
    @books = Book.order(:name)
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_reading
    @reading = Reading.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def reading_params
    params.require(:reading).permit(:body, :date, :location)
  end
end

app/helpers/readings_helper.rb
# frozen_string_literal: true

module ReadingsHelper
  def new_badge(index)
    '<span class="badge badge-secondary">New</span>'.html_safe if index.zero?
  end

  def today_badge(date)
    if date == Date.today
      '<span class="badge badge-secondary">Today</span>'.html_safe
    end
  end
end

app/views/readings/_form.html.erb
<%= form_with(model: reading, local: true) do |form| %>
  <% if reading.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reading.errors.count, "error") %> prohibited this reading from being saved:</h2>

      <ul>
        <% reading.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.rich_text_area :body, class: 'form-control' %>
    <%= form.hidden_field :reading %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_field :date, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.button 'Create Reading', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/readings/edit.html.erb
<h1>Editing Reading</h1>

<%= render 'form', reading: @reading %>

<%= link_to 'Show', @reading %> |
<%= link_to 'Back', readings_path %>

app/views/readings/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Readings</h2>
<ul class="list-group">
  <% @readings.each_with_index do |reading, index| %>
    <li class="list-group-item">
      <%= link_to "#{reading.date} -- #{reading.location}", reading %>
      <%= new_badge(index) %>
      <%= today_badge(reading.date) %>
    </li>
  <% end %>
</ul>

<br>

<%= link_to 'New Reading', new_reading_path, class: 'btn' %>

app/views/readings/new.html.erb
<h1>New Reading</h1>

<%= render 'form', reading: @reading %>

<%= link_to 'Back', readings_path %>

app/views/readings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center">
  <p>Use this space to capture questions and comments.</p>
  <p>Remember to save discussion for when we are in person!</p>
</div>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Reading</h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= @reading.date %></h6>
    <h6 class="card-subtitle mb-2 text-muted"><%= @reading.location %></h6>
    <p class="card-text"><%= @reading.body %></p>
    <%= link_to 'Edit', edit_reading_path(@reading), class: 'card-link' %>
  </div>
  <div class="card-body">
    <h5 class="card-title">Sections</h5>
    <ul class="list-group list-group-flush">
      <% @reading.sections.each do |section| %>
        <li class="list-group-item"><%= link_to section.title, section_path(section) %></li>
      <% end %>
    </ul>
    <div class="dropdown">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Add new section for
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        <% @books.each do |book| %>
          <%= link_to book.name, new_section_path(book_id: book.id, reading_id: @reading.id), class: 'dropdown-item' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-body">
    <h5 class="card-title">Reactions</h5>
    <ul class="list-group list-group-flush">
      <% @reading.reactions.ordered_by_section.each_with_index do |reaction, index| %>
        <% if reaction.verse.present? %>
          <li class="list-group-item">
            <blockquote class="blockquote mb-0">
              <p><%= reaction.link_to_anchored_verse %> <%= reaction.verse.text %></p>
              <footer class="blockquote-footer"><%= reaction.body %></footer>
            </blockquote>
          </li>
        <% else %>
         <li class="list-group-item"><%= reaction.body %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <%= render 'reactions/form', reading: @reading, reaction: Reaction.new, verse: nil, section: nil %>
</div>