config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :reactions
  root to: 'readings#index'
  resources :readings
end

app/controllers/reactions_controller.rb
# frozen_string_literal: true

class ReactionsController < ApplicationController
  before_action :set_reaction, only: %i[show edit update destroy]
  before_action :set_reading, only: [:new]
  before_action :set_section, only: [:new]
  before_action :set_verse, only: [:new]

  # GET /reactions
  # GET /reactions.json
  def index
    @reactions = Reaction.all
  end

  # GET /reactions/1
  # GET /reactions/1.json
  def show; end

  # GET /reactions/new
  def new
    @reaction = Reaction.new
  end

  # GET /reactions/1/edit
  def edit; end

  # POST /reactions
  # POST /reactions.json
  def create
    @reaction = Reaction.new(reaction_params)

    respond_to do |format|
      if @reaction.save
        format.html { redirect_to after_create_redirect, notice: 'Reaction was successfully created.' }
        format.json { render :show, status: :created, location: @reaction }
      else
        format.html { render :new }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reactions/1
  # PATCH/PUT /reactions/1.json
  def update
    respond_to do |format|
      if @reaction.update(reaction_params)
        format.html { redirect_to @reaction, notice: 'Reaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @reaction }
      else
        format.html { render :edit }
        format.json { render json: @reaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reactions/1
  # DELETE /reactions/1.json
  def destroy
    @reaction.destroy
    respond_to do |format|
      format.html { redirect_to reactions_url, notice: 'Reaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def after_create_redirect
    if @reaction.verse.present?
      @reaction.section.path_to(@reaction.verse)
    else
      reading_url(@reaction.reading)
    end
  end

  def set_reaction
    @reaction = Reaction.find(params[:id])
  end

  def set_reading
    @reading = Reading.find(params[:reading_id])
  end

  def set_section
    @section = Section.find(params[:section_id])
  end

  def set_verse
    @verse = Verse.find(params[:verse_id])
  end

  def reaction_params
    params.require(:reaction).permit(:body, :reading_id, :name, :verse_id, :section_id)
  end
end

app/helpers/reactions_helper.rb
# frozen_string_literal: true

module ReactionsHelper
end

app/views/reactions/_form.html.erb
<%= form_with(model: reaction, local: true) do |form| %>
  <% if reaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reaction.errors.count, "error") %> prohibited this reaction from being saved:</h2>

      <ul>
        <% reaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if verse.present? %>
    <h3><%= "#{verse.chapter.book.name} #{verse.chapter.number}" %></h3>
    <p><%= verse.number %>. <%= verse.text %></p>
  <% end %>

  <div class="input-group mb-3">
    <%= form.hidden_field :section_id, value: section&.id %>
    <%= form.hidden_field :verse_id, value: verse&.id %>
    <%= form.hidden_field :reading_id, value: reading.id %>
    <%= form.text_area :body, class: 'form-control', placeholder: 'Type your reaction here' %>
    <div class="input-group-append">
      <%= form.button 'Add Reaction', class: 'btn btn-outline-secondary' %>
    </div>
  </div>
<% end %>

app/views/reactions/edit.html.erb
<h1>Editing Reaction</h1>

<%= render 'form', reaction: @reaction %>

<%= link_to 'Show', @reaction %> |
<%= link_to 'Back', reactions_path %>

app/views/reactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reactions</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Reading</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reactions.each do |reaction| %>
      <tr>
        <td><%= reaction.body %></td>
        <td><%= reaction.reading_id %></td>
        <td><%= reaction.name %></td>
        <td><%= link_to 'Show', reaction %></td>
        <td><%= link_to 'Edit', edit_reaction_path(reaction) %></td>
        <td><%= link_to 'Destroy', reaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reaction', new_reaction_path %>

app/views/reactions/new.html.erb
<h1>New Reaction</h1>

<%= render 'form', reaction: @reaction, reading: @reading, section: @section, verse: @verse %>

<%= link_to 'Back', reactions_path %>

app/views/reactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @reaction.body %>
</p>

<p>
  <strong>Reading:</strong>
  <%= @reaction.reading_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @reaction.name %>
</p>

<%= link_to 'Edit', edit_reaction_path(@reaction) %> |
<%= link_to 'Back', reactions_path %>