config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :reactions
  root to: 'readings#index'
  resources :readings
end

app/models/section.rb
# frozen_string_literal: true

class Section < ApplicationRecord
  include Rails.application.routes.url_helpers

  belongs_to :book
  belongs_to :starting_chapter, class_name: 'Chapter'
  belongs_to :ending_chapter, class_name: 'Chapter'
  belongs_to :reading

  def chapters
    Chapter.where(
      book: book,
      number: (starting_chapter.number..ending_chapter.number)
    )
  end

  def title
    "#{book.name}: #{starting_chapter.number} -- #{ending_chapter.number}"
  end

  def path_to(verse)
    section_path(id: id, anchor: verse.id)
  end
end

app/controllers/sections_controller.rb
# frozen_string_literal: true

class SectionsController < ApplicationController
  before_action :set_section, only: %i[show edit update destroy]
  before_action :set_book, only: %i[edit new]
  before_action :set_reading, only: %i[edit new]

  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show; end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit; end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section.reading, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end

  def set_reading
    @reading = Reading.find(params[:reading_id])
  end

  def set_section
    @section = Section.find(params[:id])
  end

  def section_params
    params.require(:section).permit(:book_id, :starting_chapter_id, :ending_chapter_id, :reading_id)
  end
end

app/helpers/sections_helper.rb
# frozen_string_literal: true

module SectionsHelper
  def back_to(reading)
    link_to("Back to the reading #{link_svg}".html_safe, reading)
  end

  def link_svg
    Octicons::Octicon.new('link').to_svg.html_safe
  end

  def pencil_svg
    Octicons::Octicon.new('pencil').to_svg.html_safe
  end
end

app/views/sections/_form.html.erb
<%= form_with(model: section, local: true) do |form| %>
  <% if section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
        <% section.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <h3><%= @book.name %></h3>

  <%= form.hidden_field :reading_id, value: @reading.id %>
  <%= form.hidden_field :book_id, value: @book.id %>

  <div class="field">
    <%= form.label :starting_chapter_id %>
    <%= form.select :starting_chapter_id, @book.chapters.in_order.pluck(:number, :id) %>
  </div>

  <div class="field">
    <%= form.label :ending_chapter_id %>
    <%= form.select :ending_chapter_id, @book.chapters.in_order.pluck(:number, :id) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<h1>Editing Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Show', @section %> |
<%= link_to 'Back', sections_path %>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sections</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th>Starting chapter</th>
      <th>Ending chapter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.book_id %></td>
        <td><%= section.starting_chapter_id %></td>
        <td><%= section.ending_chapter_id %></td>
        <td><%= link_to 'Show', section %></td>
        <td><%= link_to 'Edit', edit_section_path(section) %></td>
        <td><%= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<h1>New Section</h1>

<%= render 'form', section: @section %>

<%= link_to 'Back', sections_path %>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @section.title %></h1>
<p><%= back_to(@section.reading) %></p>

<% @section.chapters.in_order.each do |chapter| %>
  <h2>Chapter <%= chapter.number %> <%= link_to_audio(chapter) %></h2>
  <% chapter.verses.in_order.each do |verse| %>
    <p id=<%= verse.id %>><%= verse.number %>. <%= verse.text %> <%= link_to pencil_svg, new_reaction_url(reading_id: @section.reading.id, section_id: @section.id, verse_id: verse.id) %></p>
  <% end %>
<% end %>

<p><%= back_to(@section.reading) %></p>